imported_gallery_list: list = [
                            {'Index': 0, 'Slide_Number': '1', 'Slide_Title': 'Aluminum Warehousing  |  Tutorial',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'sports',
                                'Keywords': ['global', 'aluminum', 'inventories', 'inventories', 'millions', 'metric',
                                             'tons', 'physical', 'price', 'ton', 'source', 'cru', 'privileged',
                                             'confidential', 'collar', 'collar', 'chance'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_1.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 1, 'Slide_Number': '2', 'Slide_Title': 'Overview',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing', 'Keywords': ['overview'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_2.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 2, 'Slide_Number': '3', 'Slide_Title': 'Aluminum Production and Consumption',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['chance', 'consumption', 'crisis', 'financial', 'global', 'mackenzie',
                                             'metric', 'production', 'projected', 'source', 'today', 'tons', 'wood',
                                             'aluminum', 'millions', 'load'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_3.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 3, 'Slide_Number': '4', 'Slide_Title': 'Aluminum Surplus',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['millions', 'metric', 'tons', 'aluminum', 'surplus', 'source', 'wood',
                                             'mackenzie', 'projected', 'today', 'global', 'financial', 'crisis',
                                             'surplus'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_4.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 4, 'Slide_Number': '5', 'Slide_Title': 'Production of Aluminum',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['production', 'aluminum', 'large', 'component', 'cost', 'aluminum',
                                             'power', 'consequently', 'many', 'smelters', 'located', 'cheap', 'sources',
                                             'electricity', 'such', 'hydroelectric', 'plants'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_5.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 5, 'Slide_Number': '6', 'Slide_Title': 'No Title',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['million', 'metric', 'tons', 'aluminum', 'consumed', 'united', 'states',
                                             'last', 'amount', 'less', 'produced', 'consumption', 'source', 'wood',
                                             'mackenzie'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_6.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 6, 'Slide_Number': '7', 'Slide_Title': 'Aluminum Imports | 2013',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['foreign', 'imports', 'aluminum', 'consumed', 'united', 'states', 'source',
                                             'wood', 'mackenzie'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_7.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 7, 'Slide_Number': '8', 'Slide_Title': 'Aluminum Imports | 1996 - 2013 ',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['usa', 'consumption', 'production', 'millions', 'metric', 'tons',
                                             'aluminum', 'imports', 'million', 'tonnes', 'source', 'wood', 'mackenzie'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_8.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 8, 'Slide_Number': '9', 'Slide_Title': 'Global Aluminum Inventories',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['global', 'aluminum', 'inventories', 'millions', 'metric', 'tons',
                                             'source', 'cru'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_9.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 9, 'Slide_Number': '10', 'Slide_Title': 'Aluminum Production and Consumption',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'manufacturing',
                                'Keywords': ['source', 'wood', 'mackenzie', 'surplus', 'deficit', 'million', 'tonnes',
                                             'lhs', 'rhs', 'aluminum', 'production', 'consumption', 'millions',
                                             'metric', 'tons', 'barchart'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_10.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'},
                               {'Index': 10, 'Slide_Number': '11', 'Slide_Title': 'Global Aluminum Inventories',
                                'Original_Filename': 'Aluminum Warehousing Tutorial Sanitized',
                                'Folder': '_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio', 'Type': '',
                                'Categories': 'environmental',
                                'Keywords': ['confidential', 'taco', 'boxer', 'carter', 'locker', 'cheese', 'rock',
                                             'rain', 'turkey', 'lobster', 'beach', 'cheese', 'copper', 'boston',
                                             'chipper', 'basket', 'taco', 'lover', 'burger', 'beef', 'chow'],
                                'Remote_Path': 'https://corefolio.apexdesign.app/assets/_Aluminum%20Warehousing%20Tutorial%20Sanitized_portfolio/27082023AluminumWarehousingTutorialSanitized_11.png',
                                'Dropbox_Link': 'https://www.dropbox.com/scl/fo/py1viyvfmi9tv8m2uxvf3/h/Aluminum%20Warehousing%20Tutorial%20Sanitized.pptx?rlkey=gnc0uw0i8vdpe6f2wrdjo59qx&dl=1'}
                                ]


def gsheet_to_list_of_dicts(indexed_gallery_lst) -> list:  # Simulate import from Google Sheets
    return indexed_gallery_lst


def create_local_gallery() -> list:
    local_gallery = gsheet_to_list_of_dicts(imported_gallery_list).copy()
    return local_gallery

